//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace msgtool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPXJ_Text_Export.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A072: &lt;MARK:MONEY&gt;
        ///A08D: &lt;MARK:TICK&gt;
        ///A09B: &lt;PAD:A&gt;
        ///A09C: &lt;PAD:B&gt;
        ///A09D: &lt;PAD:X&gt;
        ///A09E: &lt;PAD:Y&gt;
        ///A09F: &lt;PAD:L&gt;
        ///A0A0: &lt;PAD:R&gt;
        ///A0AB: &lt;STICK&gt;
        ///A0AC: &lt;STICK:UP_DOWN&gt;
        ///A0BB: &lt;DPAD&gt;
        ///A0BC: &lt;DPAD:UP_DOWN&gt;
        ///A0BD: &lt;DPAD_LEFT_RIGHT&gt;
        ///A0XX: &lt;MARK:0XX&gt;
        ///A1XX: &lt;MARK:1XX&gt;
        ///A2XX YYYY: &lt;CLIENT:YYYY&gt;
        ///A3XX YYYY: &lt;QUEST_ITEM:YYYY&gt;
        ///A4XX: &lt;A4XX&gt;
        ///A5XX: &lt;A5XX&gt;
        ///A6XX: &lt;A6XX&gt;
        ///A7XX: &lt;A7XX&gt;
        ///A8XX: &lt;A8XX&gt;
        ///A9XX: &lt;A9XX&gt;
        ///AAXX: &lt;AAXX&gt;
        ///ABXX: &lt;ABXX&gt;
        ///ACXX: &lt;ACXX&gt;
        ///ADXX: &lt;ADXX&gt;
        ///AEXX: &lt;AEXX&gt;
        ///AFXX: &lt;AFXX&gt;
        ///
        ///B0XX YYYY: &lt;STATUS_N:Y [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ctrl {
            get {
                return ResourceManager.GetString("ctrl", resourceCulture);
            }
        }
    }
}
